export const LOCATIONS = [
  // Europe
  { value: 'France',          label: '🇫🇷 France' },
  { value: 'Belgium',         label: '🇧🇪 Belgium' },
  { value: 'Switzerland',     label: '🇨🇭 Switzerland' },
  { value: 'Luxembourg',      label: '🇱🇺 Luxembourg' },
  { value: 'Monaco',          label: '🇲🇨 Monaco' },
  { value: 'Germany',         label: '🇩🇪 Germany' },
  { value: 'Austria',         label: '🇦🇹 Austria' },
  { value: 'Netherlands',     label: '🇳🇱 Netherlands' },
  { value: 'United Kingdom',  label: '🇬🇧 United Kingdom' },
  { value: 'Ireland',         label: '🇮🇪 Ireland' },
  { value: 'Spain',           label: '🇪🇸 Spain' },
  { value: 'Portugal',        label: '🇵🇹 Portugal' },
  { value: 'Italy',           label: '🇮🇹 Italy' },
  { value: 'Greece',          label: '🇬🇷 Greece' },
  { value: 'Poland',          label: '🇵🇱 Poland' },
  { value: 'Czech Republic',  label: '🇨🇿 Czech Republic' },
  { value: 'Slovakia',        label: '🇸🇰 Slovakia' },
  { value: 'Hungary',         label: '🇭🇺 Hungary' },
  { value: 'Romania',         label: '🇷🇴 Romania' },
  { value: 'Bulgaria',        label: '🇧🇬 Bulgaria' },
  { value: 'Croatia',         label: '🇭🇷 Croatia' },
  { value: 'Slovenia',        label: '🇸🇮 Slovenia' },
  { value: 'Serbia',          label: '🇷🇸 Serbia' },
  { value: 'Sweden',          label: '🇸🇪 Sweden' },
  { value: 'Norway',          label: '🇳🇴 Norway' },
  { value: 'Denmark',         label: '🇩🇰 Denmark' },
  { value: 'Finland',         label: '🇫🇮 Finland' },
  { value: 'Iceland',         label: '🇮🇸 Iceland' },
  { value: 'Russia',          label: '🇷🇺 Russia' },
  { value: 'Ukraine',         label: '🇺🇦 Ukraine' },
  { value: 'Turkey',          label: '🇹🇷 Turkey' },
  // Americas
  { value: 'United States',   label: '🇺🇸 United States' },
  { value: 'Canada',          label: '🇨🇦 Canada' },
  { value: 'Mexico',          label: '🇲🇽 Mexico' },
  { value: 'Brazil',          label: '🇧🇷 Brazil' },
  { value: 'Argentina',       label: '🇦🇷 Argentina' },
  { value: 'Chile',           label: '🇨🇱 Chile' },
  { value: 'Colombia',        label: '🇨🇴 Colombia' },
  { value: 'Peru',            label: '🇵🇪 Peru' },
  { value: 'Venezuela',       label: '🇻🇪 Venezuela' },
  { value: 'Uruguay',         label: '🇺🇾 Uruguay' },
  // Middle East & Africa
  { value: 'United Arab Emirates', label: '🇦🇪 United Arab Emirates' },
  { value: 'Saudi Arabia',    label: '🇸🇦 Saudi Arabia' },
  { value: 'Israel',          label: '🇮🇱 Israel' },
  { value: 'Egypt',           label: '🇪🇬 Egypt' },
  { value: 'Morocco',         label: '🇲🇦 Morocco' },
  { value: 'Algeria',         label: '🇩🇿 Algeria' },
  { value: 'Tunisia',         label: '🇹🇳 Tunisia' },
  { value: 'South Africa',    label: '🇿🇦 South Africa' },
  { value: 'Nigeria',         label: '🇳🇬 Nigeria' },
  { value: 'Kenya',           label: '🇰🇪 Kenya' },
  // Asia & Pacific
  { value: 'India',           label: '🇮🇳 India' },
  { value: 'China',           label: '🇨🇳 China' },
  { value: 'Japan',           label: '🇯🇵 Japan' },
  { value: 'South Korea',     label: '🇰🇷 South Korea' },
  { value: 'Singapore',       label: '🇸🇬 Singapore' },
  { value: 'Hong Kong',       label: '🇭🇰 Hong Kong' },
  { value: 'Taiwan',          label: '🇹🇼 Taiwan' },
  { value: 'Indonesia',       label: '🇮🇩 Indonesia' },
  { value: 'Malaysia',        label: '🇲🇾 Malaysia' },
  { value: 'Thailand',        label: '🇹🇭 Thailand' },
  { value: 'Vietnam',         label: '🇻🇳 Vietnam' },
  { value: 'Philippines',     label: '🇵🇭 Philippines' },
  { value: 'Pakistan',        label: '🇵🇰 Pakistan' },
  { value: 'Bangladesh',      label: '🇧🇩 Bangladesh' },
  { value: 'Australia',       label: '🇦🇺 Australia' },
  { value: 'New Zealand',     label: '🇳🇿 New Zealand' },
];

export const LANGUAGES = [
  { value: 'French',              label: 'Français' },
  { value: 'English',             label: 'English' },
  { value: 'German',              label: 'Deutsch' },
  { value: 'Spanish',             label: 'Español' },
  { value: 'Italian',             label: 'Italiano' },
  { value: 'Dutch',               label: 'Nederlands' },
  { value: 'Portuguese',          label: 'Português' },
  { value: 'Polish',              label: 'Polski' },
  { value: 'Russian',             label: 'Русский' },
  { value: 'Ukrainian',           label: 'Українська' },
  { value: 'Czech',               label: 'Čeština' },
  { value: 'Slovak',              label: 'Slovenčina' },
  { value: 'Hungarian',           label: 'Magyar' },
  { value: 'Romanian',            label: 'Română' },
  { value: 'Bulgarian',           label: 'Български' },
  { value: 'Croatian',            label: 'Hrvatski' },
  { value: 'Swedish',             label: 'Svenska' },
  { value: 'Norwegian',           label: 'Norsk' },
  { value: 'Danish',              label: 'Dansk' },
  { value: 'Finnish',             label: 'Suomi' },
  { value: 'Greek',               label: 'Ελληνικά' },
  { value: 'Turkish',             label: 'Türkçe' },
  { value: 'Arabic',              label: 'العربية' },
  { value: 'Hebrew',              label: 'עברית' },
  { value: 'Persian',             label: 'فارسی' },
  { value: 'Hindi',               label: 'हिन्दी' },
  { value: 'Bengali',             label: 'বাংলা' },
  { value: 'Indonesian',          label: 'Bahasa Indonesia' },
  { value: 'Malay',               label: 'Bahasa Melayu' },
  { value: 'Vietnamese',          label: 'Tiếng Việt' },
  { value: 'Thai',                label: 'ภาษาไทย' },
  { value: 'Chinese Simplified',  label: '中文 (简体)' },
  { value: 'Chinese Traditional', label: '中文 (繁體)' },
  { value: 'Japanese',            label: '日本語' },
  { value: 'Korean',              label: '한국어' },
];
